### ISSUE TITLE
The logo at the top of the README looks cropped

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [Extraweich/homopy#23]
In the README the logo image appears cropped on the right: 

![Screenshot from 2023-07-07 13-19-41](https://github.com/Extraweich/homopy/assets/8392709/61442b39-c21c-4fdc-9513-8a4a535c314f)

Upon inspection with Inkscape, I found that the background/page for your logo svg does not cover the full image, causing the preview to look cropped. 
 
![Screenshot from 2023-07-07 13-26-05](https://github.com/Extraweich/homopy/assets/8392709/68484e09-36b0-42a8-97c4-7de1525ace3b)

**Comment by Extraweich** [comment]
Hi @Kevin-Mattheus-Moerman, thank you for pointing this out. What browser do you use? I checked with Safari, Firefox and Edge with three different devices and cannot reproduce the cropping effect. If I check the file on Github, it seems fully covered:

<img width="1111" alt="Screenshot 2023-07-07 at 14 54 04" src="https://github.com/Extraweich/homopy/assets/50912803/d5116a02-f04e-4f2a-a1a0-153e450f1806">

I downloaded it and cross checked with Inkscape:

<img width="398" alt="Screenshot 2023-07-07 at 14 57 18" src="https://github.com/Extraweich/homopy/assets/50912803/5ce7783f-fcfd-4aa2-9d4e-8b1f20e591bf">

The font in your screenshots seems somewhat off. I get the same when I visit the page on my mobile phone. I will accept your PR. Please let me know if this fixed the issue for you.

**Comment by Kevin-Mattheus-Moerman** [comment]
@Extraweich I use FireFox on Ubuntu Linux. I guess it might be that the font is different which extended it? Perhaps it is some proprietary font that Ubuntu doesn't have? Odd. Anyway, it seems fixed now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@Extraweich It looks fixed now.
